name: Build Cross-Platform Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install python-docx icalendar
   
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: Build with PyInstaller (Windows & Linux)
      if: matrix.os != 'macos-latest'
      run: |
        pyinstaller --onefile --windowed --icon icons/employee-shift-calendar-generator.ico --name ShiftCalendarGenerator-v1.3.4-${{ matrix.os }} src/employee-shift-calendar-generator.py

    - name: Build with PyInstaller (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --windowed --icon icons/employee-shift-calendar-generator.icns --name ShiftCalendarGenerator-v1.3.4 src/employee-shift-calendar-generator.py
        # Create a zip of the .app bundle for easier distribution
        cd dist
        zip -r ShiftCalendarGenerator-v1.3.4-${{ matrix.os }}.zip ShiftCalendarGenerator-v1.3.4.app
    
    - name: Upload artifacts (Windows & Linux)
      if: matrix.os != 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ShiftCalendarGenerator-${{ matrix.os }}
        path: |
          dist/ShiftCalendarGenerator-v1.3.4-${{ matrix.os }}*

    - name: Upload artifacts (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ShiftCalendarGenerator-${{ matrix.os }}
        path: |
          dist/ShiftCalendarGenerator-v1.3.4.app
          dist/ShiftCalendarGenerator-v1.3.4-${{ matrix.os }}.zip

    - name: Create Release (Windows & Linux)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.os != 'macos-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/ShiftCalendarGenerator-v1.3.4-${{ matrix.os }}*
        tag_name: v1.3.4
        name: Release v1.3.4
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release (macOS)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/ShiftCalendarGenerator-v1.3.4-${{ matrix.os }}.zip
        tag_name: v1.3.4
        name: Release v1.3.4
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
